name = "nymrel-ecosystem-portal"
pages_build_output_dir = "dist"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
PORTAL_NAME = "Nymrel Open Source Agent Ecosystem Portal"
